# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cian/传感器_豆包/Sensor/Sensor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cian/传感器_豆包/Sensor/Sensor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cian/传感器_豆包/Sensor/Sensor/CMakeFiles /home/cian/传感器_豆包/Sensor/Sensor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cian/传感器_豆包/Sensor/Sensor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ForestBreedMonitor

# Build rule for target.
ForestBreedMonitor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ForestBreedMonitor
.PHONY : ForestBreedMonitor

# fast build rule for target.
ForestBreedMonitor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/build
.PHONY : ForestBreedMonitor/fast

#=============================================================================
# Target rules for targets named ForestBreedMonitor_autogen_timestamp_deps

# Build rule for target.
ForestBreedMonitor_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ForestBreedMonitor_autogen_timestamp_deps
.PHONY : ForestBreedMonitor_autogen_timestamp_deps

# fast build rule for target.
ForestBreedMonitor_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor_autogen_timestamp_deps.dir/build.make CMakeFiles/ForestBreedMonitor_autogen_timestamp_deps.dir/build
.PHONY : ForestBreedMonitor_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ForestBreedMonitor_autogen

# Build rule for target.
ForestBreedMonitor_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ForestBreedMonitor_autogen
.PHONY : ForestBreedMonitor_autogen

# fast build rule for target.
ForestBreedMonitor_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor_autogen.dir/build.make CMakeFiles/ForestBreedMonitor_autogen.dir/build
.PHONY : ForestBreedMonitor_autogen/fast

ForestBreedMonitor_autogen/mocs_compilation.o: ForestBreedMonitor_autogen/mocs_compilation.cpp.o
.PHONY : ForestBreedMonitor_autogen/mocs_compilation.o

# target to build an object file
ForestBreedMonitor_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/ForestBreedMonitor_autogen/mocs_compilation.cpp.o
.PHONY : ForestBreedMonitor_autogen/mocs_compilation.cpp.o

ForestBreedMonitor_autogen/mocs_compilation.i: ForestBreedMonitor_autogen/mocs_compilation.cpp.i
.PHONY : ForestBreedMonitor_autogen/mocs_compilation.i

# target to preprocess a source file
ForestBreedMonitor_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/ForestBreedMonitor_autogen/mocs_compilation.cpp.i
.PHONY : ForestBreedMonitor_autogen/mocs_compilation.cpp.i

ForestBreedMonitor_autogen/mocs_compilation.s: ForestBreedMonitor_autogen/mocs_compilation.cpp.s
.PHONY : ForestBreedMonitor_autogen/mocs_compilation.s

# target to generate assembly for a file
ForestBreedMonitor_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/ForestBreedMonitor_autogen/mocs_compilation.cpp.s
.PHONY : ForestBreedMonitor_autogen/mocs_compilation.cpp.s

src/business/AcquisitionManager.o: src/business/AcquisitionManager.cpp.o
.PHONY : src/business/AcquisitionManager.o

# target to build an object file
src/business/AcquisitionManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/business/AcquisitionManager.cpp.o
.PHONY : src/business/AcquisitionManager.cpp.o

src/business/AcquisitionManager.i: src/business/AcquisitionManager.cpp.i
.PHONY : src/business/AcquisitionManager.i

# target to preprocess a source file
src/business/AcquisitionManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/business/AcquisitionManager.cpp.i
.PHONY : src/business/AcquisitionManager.cpp.i

src/business/AcquisitionManager.s: src/business/AcquisitionManager.cpp.s
.PHONY : src/business/AcquisitionManager.s

# target to generate assembly for a file
src/business/AcquisitionManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/business/AcquisitionManager.cpp.s
.PHONY : src/business/AcquisitionManager.cpp.s

src/business/DataProcessor.o: src/business/DataProcessor.cpp.o
.PHONY : src/business/DataProcessor.o

# target to build an object file
src/business/DataProcessor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/business/DataProcessor.cpp.o
.PHONY : src/business/DataProcessor.cpp.o

src/business/DataProcessor.i: src/business/DataProcessor.cpp.i
.PHONY : src/business/DataProcessor.i

# target to preprocess a source file
src/business/DataProcessor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/business/DataProcessor.cpp.i
.PHONY : src/business/DataProcessor.cpp.i

src/business/DataProcessor.s: src/business/DataProcessor.cpp.s
.PHONY : src/business/DataProcessor.s

# target to generate assembly for a file
src/business/DataProcessor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/business/DataProcessor.cpp.s
.PHONY : src/business/DataProcessor.cpp.s

src/camera/CameraManager.o: src/camera/CameraManager.cpp.o
.PHONY : src/camera/CameraManager.o

# target to build an object file
src/camera/CameraManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/camera/CameraManager.cpp.o
.PHONY : src/camera/CameraManager.cpp.o

src/camera/CameraManager.i: src/camera/CameraManager.cpp.i
.PHONY : src/camera/CameraManager.i

# target to preprocess a source file
src/camera/CameraManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/camera/CameraManager.cpp.i
.PHONY : src/camera/CameraManager.cpp.i

src/camera/CameraManager.s: src/camera/CameraManager.cpp.s
.PHONY : src/camera/CameraManager.s

# target to generate assembly for a file
src/camera/CameraManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/camera/CameraManager.cpp.s
.PHONY : src/camera/CameraManager.cpp.s

src/common/Config.o: src/common/Config.cpp.o
.PHONY : src/common/Config.o

# target to build an object file
src/common/Config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/common/Config.cpp.o
.PHONY : src/common/Config.cpp.o

src/common/Config.i: src/common/Config.cpp.i
.PHONY : src/common/Config.i

# target to preprocess a source file
src/common/Config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/common/Config.cpp.i
.PHONY : src/common/Config.cpp.i

src/common/Config.s: src/common/Config.cpp.s
.PHONY : src/common/Config.s

# target to generate assembly for a file
src/common/Config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/common/Config.cpp.s
.PHONY : src/common/Config.cpp.s

src/common/Logger.o: src/common/Logger.cpp.o
.PHONY : src/common/Logger.o

# target to build an object file
src/common/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/common/Logger.cpp.o
.PHONY : src/common/Logger.cpp.o

src/common/Logger.i: src/common/Logger.cpp.i
.PHONY : src/common/Logger.i

# target to preprocess a source file
src/common/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/common/Logger.cpp.i
.PHONY : src/common/Logger.cpp.i

src/common/Logger.s: src/common/Logger.cpp.s
.PHONY : src/common/Logger.s

# target to generate assembly for a file
src/common/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/common/Logger.cpp.s
.PHONY : src/common/Logger.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/net/MockServer.o: src/net/MockServer.cpp.o
.PHONY : src/net/MockServer.o

# target to build an object file
src/net/MockServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/net/MockServer.cpp.o
.PHONY : src/net/MockServer.cpp.o

src/net/MockServer.i: src/net/MockServer.cpp.i
.PHONY : src/net/MockServer.i

# target to preprocess a source file
src/net/MockServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/net/MockServer.cpp.i
.PHONY : src/net/MockServer.cpp.i

src/net/MockServer.s: src/net/MockServer.cpp.s
.PHONY : src/net/MockServer.s

# target to generate assembly for a file
src/net/MockServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/net/MockServer.cpp.s
.PHONY : src/net/MockServer.cpp.s

src/net/TcpClient.o: src/net/TcpClient.cpp.o
.PHONY : src/net/TcpClient.o

# target to build an object file
src/net/TcpClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/net/TcpClient.cpp.o
.PHONY : src/net/TcpClient.cpp.o

src/net/TcpClient.i: src/net/TcpClient.cpp.i
.PHONY : src/net/TcpClient.i

# target to preprocess a source file
src/net/TcpClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/net/TcpClient.cpp.i
.PHONY : src/net/TcpClient.cpp.i

src/net/TcpClient.s: src/net/TcpClient.cpp.s
.PHONY : src/net/TcpClient.s

# target to generate assembly for a file
src/net/TcpClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/net/TcpClient.cpp.s
.PHONY : src/net/TcpClient.cpp.s

src/protocol/FrameCodec.o: src/protocol/FrameCodec.cpp.o
.PHONY : src/protocol/FrameCodec.o

# target to build an object file
src/protocol/FrameCodec.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/protocol/FrameCodec.cpp.o
.PHONY : src/protocol/FrameCodec.cpp.o

src/protocol/FrameCodec.i: src/protocol/FrameCodec.cpp.i
.PHONY : src/protocol/FrameCodec.i

# target to preprocess a source file
src/protocol/FrameCodec.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/protocol/FrameCodec.cpp.i
.PHONY : src/protocol/FrameCodec.cpp.i

src/protocol/FrameCodec.s: src/protocol/FrameCodec.cpp.s
.PHONY : src/protocol/FrameCodec.s

# target to generate assembly for a file
src/protocol/FrameCodec.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/protocol/FrameCodec.cpp.s
.PHONY : src/protocol/FrameCodec.cpp.s

src/storage/SqliteStorage.o: src/storage/SqliteStorage.cpp.o
.PHONY : src/storage/SqliteStorage.o

# target to build an object file
src/storage/SqliteStorage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/storage/SqliteStorage.cpp.o
.PHONY : src/storage/SqliteStorage.cpp.o

src/storage/SqliteStorage.i: src/storage/SqliteStorage.cpp.i
.PHONY : src/storage/SqliteStorage.i

# target to preprocess a source file
src/storage/SqliteStorage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/storage/SqliteStorage.cpp.i
.PHONY : src/storage/SqliteStorage.cpp.i

src/storage/SqliteStorage.s: src/storage/SqliteStorage.cpp.s
.PHONY : src/storage/SqliteStorage.s

# target to generate assembly for a file
src/storage/SqliteStorage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/storage/SqliteStorage.cpp.s
.PHONY : src/storage/SqliteStorage.cpp.s

src/ui/MainWindow.o: src/ui/MainWindow.cpp.o
.PHONY : src/ui/MainWindow.o

# target to build an object file
src/ui/MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/ui/MainWindow.cpp.o
.PHONY : src/ui/MainWindow.cpp.o

src/ui/MainWindow.i: src/ui/MainWindow.cpp.i
.PHONY : src/ui/MainWindow.i

# target to preprocess a source file
src/ui/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/ui/MainWindow.cpp.i
.PHONY : src/ui/MainWindow.cpp.i

src/ui/MainWindow.s: src/ui/MainWindow.cpp.s
.PHONY : src/ui/MainWindow.s

# target to generate assembly for a file
src/ui/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ForestBreedMonitor.dir/build.make CMakeFiles/ForestBreedMonitor.dir/src/ui/MainWindow.cpp.s
.PHONY : src/ui/MainWindow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ForestBreedMonitor_autogen"
	@echo "... ForestBreedMonitor_autogen_timestamp_deps"
	@echo "... ForestBreedMonitor"
	@echo "... ForestBreedMonitor_autogen/mocs_compilation.o"
	@echo "... ForestBreedMonitor_autogen/mocs_compilation.i"
	@echo "... ForestBreedMonitor_autogen/mocs_compilation.s"
	@echo "... src/business/AcquisitionManager.o"
	@echo "... src/business/AcquisitionManager.i"
	@echo "... src/business/AcquisitionManager.s"
	@echo "... src/business/DataProcessor.o"
	@echo "... src/business/DataProcessor.i"
	@echo "... src/business/DataProcessor.s"
	@echo "... src/camera/CameraManager.o"
	@echo "... src/camera/CameraManager.i"
	@echo "... src/camera/CameraManager.s"
	@echo "... src/common/Config.o"
	@echo "... src/common/Config.i"
	@echo "... src/common/Config.s"
	@echo "... src/common/Logger.o"
	@echo "... src/common/Logger.i"
	@echo "... src/common/Logger.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/net/MockServer.o"
	@echo "... src/net/MockServer.i"
	@echo "... src/net/MockServer.s"
	@echo "... src/net/TcpClient.o"
	@echo "... src/net/TcpClient.i"
	@echo "... src/net/TcpClient.s"
	@echo "... src/protocol/FrameCodec.o"
	@echo "... src/protocol/FrameCodec.i"
	@echo "... src/protocol/FrameCodec.s"
	@echo "... src/storage/SqliteStorage.o"
	@echo "... src/storage/SqliteStorage.i"
	@echo "... src/storage/SqliteStorage.s"
	@echo "... src/ui/MainWindow.o"
	@echo "... src/ui/MainWindow.i"
	@echo "... src/ui/MainWindow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

